use november;

CREATE TABLE Books (
    book_id INT PRIMARY KEY,
    title VARCHAR(100) NOT NULL UNIQUE,
    author VARCHAR(100) NOT NULL,
    genre VARCHAR(50),
    price DECIMAL(6,2) CHECK (price > 0),
    publication_year INT
);

-- 2. Create Orders Table
CREATE TABLE Orders (
    order_id INT PRIMARY KEY,
    book_id INT NOT NULL,
    customer_name VARCHAR(100) NOT NULL,
    order_date DATE NOT NULL,
    quantity INT CHECK (quantity > 0),
    total_price DECIMAL(8,2) CHECK (total_price >= 0),
    FOREIGN KEY (book_id) REFERENCES Books(book_id)
);


INSERT INTO Books (book_id, title, author, genre, price, publication_year)
VALUES
(1, 'The Silent Patient', 'Alex Michaelides', 'Thriller', 499.00, 2019),
(2, 'Where the Crawdads Sing', 'Delia Owens', 'Fiction', 399.00, 2018),
(3, 'Atomic Habits', 'James Clear', 'Self Help', 599.00, 2018),
(4, 'The Midnight Library', 'Matt Haig', 'Fiction', 450.00, 2020),
(5, 'Educated', 'Tara Westover', 'Memoir', 550.00, 2018),
(6, 'Becoming', 'Michelle Obama', 'Memoir', 650.00, 2018),
(7, 'The Alchemist', 'Paulo Coelho', 'Philosophical', 350.00, 1988),
(8, 'Verity', 'Colleen Hoover', 'Thriller', 499.00, 2021),
(9, 'It Ends With Us', 'Colleen Hoover', 'Romance', 459.00, 2016),
(10, 'It Starts With Us', 'Colleen Hoover', 'Romance', 499.00, 2022);


INSERT INTO Orders (order_id, book_id, customer_name, order_date, quantity, total_price)
VALUES
(1, 1, 'Riya Mehta', '2023-01-15', 1, 499.00),
(2, 2, 'Arjun Patel', '2023-02-01', 2, 798.00),
(3, 3, 'Priya Sharma', '2023-02-10', 1, 599.00),
(4, 4, 'Riya Mehta', '2023-03-05', 1, 450.00),
(5, 5, 'Vikram Joshi', '2023-03-15', 1, 550.00),
(6, 6, 'Neha Kapoor', '2023-03-20', 2, 1300.00),
(7, 7, 'Ravi Deshmukh', '2023-03-25', 1, 350.00),
(8, 8, 'Riya Mehta', '2023-04-10', 1, 499.00),
(9, 9, 'Arjun Patel', '2023-05-01', 2, 918.00),
(10, 10, 'Arjun Patel', '2023-05-15', 1, 499.00),
(11, 3, 'Riya Mehta', '2023-06-05', 1, 599.00),
(12, 9, 'Priya Sharma', '2023-06-15', 1, 459.00);


-- Find the most expensive book in the store
select title
from books
where price = (select max(price) from books);

-- Find books whose price is higher than the average price of books in the same genre
select title
from books as b
where price > (select avg(price) from books where b.genre = genre);

-- Find the total revenue generated by each author
select b.author, sum(o.total_price) as total_revenue
from books as b
join orders as o on b.book_id = o.book_id
group by b.author;

-- Provide the rank of books based on the price
select title, price,
rank() over(order by price desc) as ranking
from books;

-- Compute the running total of revenue from book sales over time
select order_date, sum(total_price) as revenue,
sum(sum(total_price)) over(order by order_date) as running_total
from orders
group by order_date
order by order_date;

-- Find books written by the same author
select author, title
from books
where author in (select author from books group by author having count(*) > 1)
order by author, title;

-- Find the book that generated the highest total revenue
select b.book_id, b.title, sum(o.total_price) as total_revenue 
from books as b
join orders as o on b.book_id = o.book_id 
group by b.book_id, b.title
order by total_revenue desc
limit 1;

-- Find customers who placed more than one order
SELECT DISTINCT o1.customer_name
FROM Orders o1
WHERE (
    SELECT COUNT(*) 
    FROM Orders o2
    WHERE o2.customer_name = o1.customer_name
) > 1;

-- Find the book name and price with the second-highest price
SELECT 
    title,
    price
FROM Books
WHERE price = (
    SELECT DISTINCT price
    FROM Books
    ORDER BY price DESC
    LIMIT 1 OFFSET 1
);

With bookRank as (
    select title, price,
    dense_rank() over (order by price desc) as price_rank
    from Books)
select *
FROM bookRank
where price_rank = 2;

-- Find authors who have written multiple books and count how many books they have written
SELECT 
    author,
    COUNT(*) AS book_count
FROM Books
GROUP BY author
HAVING COUNT(*) > 1
ORDER BY book_count DESC;




 


